### ISSUE TITLE
[Project - Onboarding]: Implement telemetry in each step of the onboarding flow

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/addon-onboarding#39]
## Description:

The goal of this task is to instrument the @storybook/addon-onboarding application to send specific telemetry events during the onboarding process. These events cover various steps in the onboarding flow, as well as user interactions with the interface. The telemetry data should be sent to the Node.js server from the browser using the tracking function implemented in a previous task.

## Acceptance Criteria:

The application should send telemetry events for the following:

- Started onboarding
- Skipped onboarding (where was it triggered)
- Finished Step-by-Step Tour
- Finished How-to-write-your-Story Tour
- Finished completely

All events should contain relevant data (if any), and should be sent at the appropriate times during the onboarding process.

## Edge Cases to Consider:

- **Event firing reliability**: The application should reliably send events even in the face of network interruptions or other issues.
- **Event ordering**: The sequence of events should accurately reflect the order of the user's actions and the onboarding process.

**Comment by shilman** [comment]
List so far:
- [ ] browser viewport size
